language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vamseekrishnakattika/react-docker -f Dockefile.dev .

script:
  - docker run -e CI=true vamseekrishnakattika/react-docker npm run test